# Nama pipeline
name: DevSecOps CI Pipeline

# Pemicu: Inilah "aturan" yang Anda inginkan
on:
  # Berjalan saat ada push atau merge ke main
  push:
    branches: [ "main" ]
  # Berjalan saat ada Pull Request dibuka atau diupdate untuk branch main
  pull_request:
    branches: [ "main" ]

# Daftar pekerjaan yang akan dieksekusi
jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Kode'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      
      - name: 'Install Dependensi Composer'
        run: composer install --prefer-dist --no-progress

      - name: 'SonarQube Scan (SAST)'
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
